""" This module  """

class MockRequestsGet1:
    def __init__(self, url, params=None):
        self.status_code = 200
    def json(self):
        return {'results': [{'address_components': [{'long_name': '5',
                                'short_name': '5',
                                'types': ['street_number']},
                                {'long_name': 'Rue St. John Perse',
                                'short_name': 'Rue St. John Perse',
                                'types': ['route']},
                                {'long_name': 'Pointe-à-Pitre',
                                'short_name': 'Pointe-à-Pitre',
                                'types': ['locality', 'political']},
                                {'long_name': 'Les Abymes',
                                'short_name': 'Les Abymes',
                                'types': ['administrative_area_level_2',
                                        'political']},
                                {'long_name': 'Grande-Terre',
                                'short_name': 'Grande-Terre',
                                'types': ['administrative_area_level_1',
                                        'political']},
                                {'long_name': 'Guadeloupe',
                                'short_name': 'GP',
                                'types': ['country', 'political']}],
                        'formatted_address': '5 Rue St. John Perse, Pointe-à-Pitre, '
                                            'Guadeloupe',
                        'geometry': {'location': {'lat': 16.2365431, 'lng': -61.5344845},
                                    'location_type': 'ROOFTOP',
                                    'viewport': {'northeast': {'lat': 16.2378920802915,
                                                                'lng': -61.53313551970849},
                                                    'southwest': {'lat': 16.2351941197085,
                                                                'lng': -61.5358334802915}}},
                        'place_id': 'ChIJj7dFAuFFE4wRP6_DhDQX6Es',
                        'plus_code': {'compound_code': '6FP8+J6 Pointe-à-Pitre, '
                                                        'Guadeloupe',
                                        'global_code': '778W6FP8+J6'},
                        'types': ['establishment',
                                    'point_of_interest',
                                    'tourist_attraction']}],
            'status': 'OK'}


EXPECTED_RESULT_9 = (200,
 [{'dist': 15.6,
   'lat': 48.8523,
   'lon': 2.370164,
   'ns': 0,
   'pageid': 879189,
   'primary': '',
   'title': 'Gare de Paris-Bastille'},
  {'dist': 35.9,
   'lat': 48.8525,
   'lon': 2.369722,
   'ns': 0,
   'pageid': 4705311,
   'primary': '',
   'title': 'Laudator Temporis'},
  {'dist': 56.2,
   'lat': 48.85274,
   'lon': 2.37082,
   'ns': 0,
   'pageid': 691978,
   'primary': '',
   'title': 'Hôpital des Enfants-Trouvés'},
  {'dist': 86.5,
   'lat': 48.8530918,
   'lon': 2.3695634,
   'ns': 0,
   'pageid': 23299,
   'primary': '',
   'title': 'Place de la Bastille'},
  {'dist': 90.1,
   'lat': 48.85222,
   'lon': 2.37139,
   'ns': 0,
   'pageid': 132448,
   'primary': '',
   'title': 'Rue de Charenton'},
  {'dist': 91.6,
   'lat': 48.85174,
   'lon': 2.36954,
   'ns': 0,
   'pageid': 5930481,
   'primary': '',
   'title': "Immeuble de l'îlot Biscornet"},
  {'dist': 102.3,
   'lat': 48.853055555556,
   'lon': 2.3691666666667,
   'ns': 0,
   'pageid': 104235,
   'primary': '',
   'title': 'Colonne de Juillet'},
  {'dist': 102.3,
   'lat': 48.853055555556,
   'lon': 2.3691666666667,
   'ns': 0,
   'pageid': 23298,
   'primary': '',
   'title': 'Prise de la Bastille'},
  {'dist': 109.2,
   'lat': 48.853082,
   'lon': 2.369077,
   'ns': 0,
   'pageid': 52483,
   'primary': '',
   'title': 'Bastille (métro de Paris)'},
  {'dist': 112.3,
   'lat': 48.85295,
   'lon': 2.371526,
   'ns': 0,
   'pageid': 5425002,
   'primary': '',
   'title': 'Cité Parchappe'},
  {'dist': 116.7,
   'lat': 48.85324,
   'lon': 2.369174,
   'ns': 0,
   'pageid': 7123269,
   'primary': '',
   'title': 'Le Génie de la Liberté'},
  {'dist': 117.3,
   'lat': 48.85335,
   'lon': 2.371011,
   'ns': 0,
   'pageid': 5419878,
   'primary': '',
   'title': 'Passage du Cheval-Blanc'},
  {'dist': 125.1,
   'lat': 48.853333,
   'lon': 2.369167,
   'ns': 0,
   'pageid': 76907,
   'primary': '',
   'title': 'Bastille'},
  {'dist': 160.9,
   'lat': 48.853885,
   'lon': 2.37019,
   'ns': 0,
   'pageid': 5425026,
   'primary': '',
   'title': 'Cour Damoye'},
  {'dist': 172.7,
   'lat': 48.85138889,
   'lon': 2.37194444,
   'ns': 0,
   'pageid': 4918486,
   'primary': '',
   'title': 'Caserne des Mousquetaires-Noirs'},
  {'dist': 189.6,
   'lat': 48.8527558,
   'lon': 2.37275,
   'ns': 0,
   'pageid': 5425049,
   'primary': '',
   'title': 'Cour Saint-Louis'},
  {'dist': 192.5,
   'lat': 48.85379,
   'lon': 2.36856,
   'ns': 0,
   'pageid': 972432,
   'primary': '',
   'title': 'Porte Saint-Antoine'},
  {'dist': 192.6,
   'lat': 48.85361,
   'lon': 2.3682639,
   'ns': 0,
   'pageid': 1275452,
   'primary': '',
   'title': 'Café des Phares'},
  {'dist': 195.4,
   'lat': 48.853882,
   'lon': 2.371725,
   'ns': 0,
   'pageid': 5425024,
   'primary': '',
   'title': 'Cour du Cantal'},
  {'dist': 195.4,
   'lat': 48.85193,
   'lon': 2.37276,
   'ns': 0,
   'pageid': 4576249,
   'primary': '',
   'title': 'Passage de la Boule-Blanche'},
  {'dist': 200.3,
   'lat': 48.8533,
   'lon': 2.3678,
   'ns': 0,
   'pageid': 7883284,
   'primary': '',
   'title': 'Tour de la Liberté (Paris)'},
  {'dist': 208.1,
   'lat': 48.852408,
   'lon': 2.373047,
   'ns': 0,
   'pageid': 5425041,
   'primary': '',
   'title': 'Cour du Nom-de-Jésus'},
  {'dist': 214,
   'lat': 48.85239,
   'lon': 2.36728,
   'ns': 0,
   'pageid': 5423385,
   'primary': '',
   'title': 'Rue Jacques-Cœur'},
  {'dist': 222.8,
   'lat': 48.85398,
   'lon': 2.372148,
   'ns': 0,
   'pageid': 4819455,
   'primary': '',
   'title': 'Balajo'},
  {'dist': 223.5,
   'lat': 48.85205,
   'lon': 2.3732,
   'ns': 0,
   'pageid': 3844049,
   'primary': '',
   'title': 'Cour du Bel-Air'},
  {'dist': 225.5,
   'lat': 48.853822,
   'lon': 2.367951,
   'ns': 0,
   'pageid': 3504034,
   'primary': '',
   'title': 'Rue de la Bastille (Paris)'},
  {'dist': 233.2,
   'lat': 48.8517,
   'lon': 2.36722,
   'ns': 0,
   'pageid': 4906661,
   'primary': '',
   'title': 'Sous-station Bastille'},
  {'dist': 238.2,
   'lat': 48.8535641,
   'lon': 2.3729726,
   'ns': 0,
   'pageid': 229706,
   'primary': '',
   'title': 'Rue de Lappe'},
  {'dist': 240.9,
   'lat': 48.851254,
   'lon': 2.367446,
   'ns': 0,
   'pageid': 3538666,
   'primary': '',
   'title': 'Boulevard Bourdon (Paris)'},
  {'dist': 246,
   'lat': 48.853054,
   'lon': 2.366974,
   'ns': 0,
   'pageid': 4363313,
   'primary': '',
   'title': 'Rue de Lesdiguières'},
  {'dist': 246.4,
   'lat': 48.8525246,
   'lon': 2.373568,
   'ns': 0,
   'pageid': 6802458,
   'primary': '',
   'title': 'Cour Saint-Joseph'},
  {'dist': 248,
   'lat': 48.851328,
   'lon': 2.367264,
   'ns': 0,
   'pageid': 12608471,
   'primary': '',
   'title': "L'Ascenseur (incubateur associatif)"},
  {'dist': 250.2,
   'lat': 48.852175,
   'lon': 2.373599,
   'ns': 0,
   'pageid': 5425054,
   'primary': '',
   'title': 'Cour Viguès'},
  {'dist': 250.2,
   'lat': 48.8521805,
   'lon': 2.3736002,
   'ns': 0,
   'pageid': 6802485,
   'primary': '',
   'title': 'Cour Jacques-Viguès'},
  {'dist': 250.9,
   'lat': 48.850195,
   'lon': 2.36983,
   'ns': 0,
   'pageid': 4580206,
   'primary': '',
   'title': 'Rue Biscornet'},
  {'dist': 256.6,
   'lat': 48.854296,
   'lon': 2.368122,
   'ns': 0,
   'pageid': 5423404,
   'primary': '',
   'title': 'Rue Jean-Beausire'},
  {'dist': 257.8,
   'lat': 48.85472,
   'lon': 2.37083,
   'ns': 0,
   'pageid': 5348677,
   'primary': '',
   'title': 'Rue Daval'},
  {'dist': 259.2,
   'lat': 48.850127,
   'lon': 2.369746,
   'ns': 0,
   'pageid': 2945021,
   'primary': '',
   'title': 'IGN FI'},
  {'dist': 260.2,
   'lat': 48.851286,
   'lon': 2.373298,
   'ns': 0,
   'pageid': 4576312,
   'primary': '',
   'title': 'Passage du Chantier'},
  {'dist': 263.3,
   'lat': 48.852,
   'lon': 2.37374,
   'ns': 0,
   'pageid': 4105367,
   'primary': '',
   'title': 'Fontaine de Charonne'},
  {'dist': 267.7,
   'lat': 48.8548,
   'lon': 2.36949,
   'ns': 0,
   'pageid': 12306106,
   'primary': '',
   'title': 'Maison Caron de Beaumarchais'},
  {'dist': 272.3,
   'lat': 48.854051,
   'lon': 2.373004,
   'ns': 0,
   'pageid': 5419993,
   'primary': '',
   'title': 'Passage Louis-Philippe'},
  {'dist': 273.6,
   'lat': 48.854266,
   'lon': 2.3677,
   'ns': 0,
   'pageid': 5419959,
   'primary': '',
   'title': 'Passage Jean-Beausire'},
  {'dist': 290.9,
   'lat': 48.852891,
   'lon': 2.366288,
   'ns': 0,
   'pageid': 5422756,
   'primary': '',
   'title': 'Rue Castex'},
  {'dist': 292.3,
   'lat': 48.850971,
   'lon': 2.366889,
   'ns': 0,
   'pageid': 5422606,
   'primary': '',
   'title': 'Rue Bassompierre'},
  {'dist': 297.6,
   'lat': 48.853543,
   'lon': 2.373908,
   'ns': 0,
   'pageid': 5425046,
   'primary': '',
   'title': 'Cour Quellard'},
  {'dist': 302.3,
   'lat': 48.851917,
   'lon': 2.366148,
   'ns': 0,
   'pageid': 4638866,
   'primary': '',
   'title': 'Rue de la Cerisaie'},
  {'dist': 302.3,
   'lat': 48.851917,
   'lon': 2.366148,
   'ns': 0,
   'pageid': 11870991,
   'primary': '',
   'title': 'Hôtel de Lesdiguières (Paris)'},
  {'dist': 305.8,
   'lat': 48.85333,
   'lon': 2.36625,
   'ns': 0,
   'pageid': 140673,
   'primary': '',
   'title': 'Temple du Marais'},
  {'dist': 311.2,
   'lat': 48.853233,
   'lon': 2.374282,
   'ns': 0,
   'pageid': 5425043,
   'primary': '',
   'title': 'Cour du Panier-Fleuri'}])

class MockRequestsGet3:
    def __init__(self, url, params=None):
        self.status_code = 200
    def json(self):
        return {'batchcomplete': '',
                'query': {'geosearch': [{'dist': 15.6,
                                        'lat': 48.8523,
                                        'lon': 2.370164,
                                        'ns': 0,
                                        'pageid': 879189,
                                        'primary': '',
                                        'title': 'Gare de Paris-Bastille'},
                                        {'dist': 35.9,
                                        'lat': 48.8525,
                                        'lon': 2.369722,
                                        'ns': 0,
                                        'pageid': 4705311,
                                        'primary': '',
                                        'title': 'Laudator Temporis'},
                                        {'dist': 56.2,
                                        'lat': 48.85274,
                                        'lon': 2.37082,
                                        'ns': 0,
                                        'pageid': 691978,
                                        'primary': '',
                                        'title': 'Hôpital des Enfants-Trouvés'},
                                        {'dist': 86.5,
                                        'lat': 48.8530918,
                                        'lon': 2.3695634,
                                        'ns': 0,
                                        'pageid': 23299,
                                        'primary': '',
                                        'title': 'Place de la Bastille'},
                                        {'dist': 90.1,
                                        'lat': 48.85222,
                                        'lon': 2.37139,
                                        'ns': 0,
                                        'pageid': 132448,
                                        'primary': '',
                                        'title': 'Rue de Charenton'},
                                        {'dist': 91.6,
                                        'lat': 48.85174,
                                        'lon': 2.36954,
                                        'ns': 0,
                                        'pageid': 5930481,
                                        'primary': '',
                                        'title': "Immeuble de l'îlot Biscornet"},
                                        {'dist': 102.3,
                                        'lat': 48.853055555556,
                                        'lon': 2.3691666666667,
                                        'ns': 0,
                                        'pageid': 104235,
                                        'primary': '',
                                        'title': 'Colonne de Juillet'},
                                        {'dist': 102.3,
                                        'lat': 48.853055555556,
                                        'lon': 2.3691666666667,
                                        'ns': 0,
                                        'pageid': 23298,
                                        'primary': '',
                                        'title': 'Prise de la Bastille'},
                                        {'dist': 109.2,
                                        'lat': 48.853082,
                                        'lon': 2.369077,
                                        'ns': 0,
                                        'pageid': 52483,
                                        'primary': '',
                                        'title': 'Bastille (métro de Paris)'},
                                        {'dist': 112.3,
                                        'lat': 48.85295,
                                        'lon': 2.371526,
                                        'ns': 0,
                                        'pageid': 5425002,
                                        'primary': '',
                                        'title': 'Cité Parchappe'},
                                        {'dist': 116.7,
                                        'lat': 48.85324,
                                        'lon': 2.369174,
                                        'ns': 0,
                                        'pageid': 7123269,
                                        'primary': '',
                                        'title': 'Le Génie de la Liberté'},
                                        {'dist': 117.3,
                                        'lat': 48.85335,
                                        'lon': 2.371011,
                                        'ns': 0,
                                        'pageid': 5419878,
                                        'primary': '',
                                        'title': 'Passage du Cheval-Blanc'},
                                        {'dist': 125.1,
                                        'lat': 48.853333,
                                        'lon': 2.369167,
                                        'ns': 0,
                                        'pageid': 76907,
                                        'primary': '',
                                        'title': 'Bastille'},
                                        {'dist': 160.9,
                                        'lat': 48.853885,
                                        'lon': 2.37019,
                                        'ns': 0,
                                        'pageid': 5425026,
                                        'primary': '',
                                        'title': 'Cour Damoye'},
                                        {'dist': 172.7,
                                        'lat': 48.85138889,
                                        'lon': 2.37194444,
                                        'ns': 0,
                                        'pageid': 4918486,
                                        'primary': '',
                                        'title': 'Caserne des Mousquetaires-Noirs'},
                                        {'dist': 189.6,
                                        'lat': 48.8527558,
                                        'lon': 2.37275,
                                        'ns': 0,
                                        'pageid': 5425049,
                                        'primary': '',
                                        'title': 'Cour Saint-Louis'},
                                        {'dist': 192.5,
                                        'lat': 48.85379,
                                        'lon': 2.36856,
                                        'ns': 0,
                                        'pageid': 972432,
                                        'primary': '',
                                        'title': 'Porte Saint-Antoine'},
                                        {'dist': 192.6,
                                        'lat': 48.85361,
                                        'lon': 2.3682639,
                                        'ns': 0,
                                        'pageid': 1275452,
                                        'primary': '',
                                        'title': 'Café des Phares'},
                                        {'dist': 195.4,
                                        'lat': 48.853882,
                                        'lon': 2.371725,
                                        'ns': 0,
                                        'pageid': 5425024,
                                        'primary': '',
                                        'title': 'Cour du Cantal'},
                                        {'dist': 195.4,
                                        'lat': 48.85193,
                                        'lon': 2.37276,
                                        'ns': 0,
                                        'pageid': 4576249,
                                        'primary': '',
                                        'title': 'Passage de la Boule-Blanche'},
                                        {'dist': 200.3,
                                        'lat': 48.8533,
                                        'lon': 2.3678,
                                        'ns': 0,
                                        'pageid': 7883284,
                                        'primary': '',
                                        'title': 'Tour de la Liberté (Paris)'},
                                        {'dist': 208.1,
                                        'lat': 48.852408,
                                        'lon': 2.373047,
                                        'ns': 0,
                                        'pageid': 5425041,
                                        'primary': '',
                                        'title': 'Cour du Nom-de-Jésus'},
                                        {'dist': 214,
                                        'lat': 48.85239,
                                        'lon': 2.36728,
                                        'ns': 0,
                                        'pageid': 5423385,
                                        'primary': '',
                                        'title': 'Rue Jacques-Cœur'},
                                        {'dist': 222.8,
                                        'lat': 48.85398,
                                        'lon': 2.372148,
                                        'ns': 0,
                                        'pageid': 4819455,
                                        'primary': '',
                                        'title': 'Balajo'},
                                        {'dist': 223.5,
                                        'lat': 48.85205,
                                        'lon': 2.3732,
                                        'ns': 0,
                                        'pageid': 3844049,
                                        'primary': '',
                                        'title': 'Cour du Bel-Air'},
                                        {'dist': 225.5,
                                        'lat': 48.853822,
                                        'lon': 2.367951,
                                        'ns': 0,
                                        'pageid': 3504034,
                                        'primary': '',
                                        'title': 'Rue de la Bastille (Paris)'},
                                        {'dist': 233.2,
                                        'lat': 48.8517,
                                        'lon': 2.36722,
                                        'ns': 0,
                                        'pageid': 4906661,
                                        'primary': '',
                                        'title': 'Sous-station Bastille'},
                                        {'dist': 238.2,
                                        'lat': 48.8535641,
                                        'lon': 2.3729726,
                                        'ns': 0,
                                        'pageid': 229706,
                                        'primary': '',
                                        'title': 'Rue de Lappe'},
                                        {'dist': 240.9,
                                        'lat': 48.851254,
                                        'lon': 2.367446,
                                        'ns': 0,
                                        'pageid': 3538666,
                                        'primary': '',
                                        'title': 'Boulevard Bourdon (Paris)'},
                                        {'dist': 246,
                                        'lat': 48.853054,
                                        'lon': 2.366974,
                                        'ns': 0,
                                        'pageid': 4363313,
                                        'primary': '',
                                        'title': 'Rue de Lesdiguières'},
                                        {'dist': 246.4,
                                        'lat': 48.8525246,
                                        'lon': 2.373568,
                                        'ns': 0,
                                        'pageid': 6802458,
                                        'primary': '',
                                        'title': 'Cour Saint-Joseph'},
                                        {'dist': 248,
                                        'lat': 48.851328,
                                        'lon': 2.367264,
                                        'ns': 0,
                                        'pageid': 12608471,
                                        'primary': '',
                                        'title': "L'Ascenseur (incubateur associatif)"},
                                        {'dist': 250.2,
                                        'lat': 48.852175,
                                        'lon': 2.373599,
                                        'ns': 0,
                                        'pageid': 5425054,
                                        'primary': '',
                                        'title': 'Cour Viguès'},
                                        {'dist': 250.2,
                                        'lat': 48.8521805,
                                        'lon': 2.3736002,
                                        'ns': 0,
                                        'pageid': 6802485,
                                        'primary': '',
                                        'title': 'Cour Jacques-Viguès'},
                                        {'dist': 250.9,
                                        'lat': 48.850195,
                                        'lon': 2.36983,
                                        'ns': 0,
                                        'pageid': 4580206,
                                        'primary': '',
                                        'title': 'Rue Biscornet'},
                                        {'dist': 256.6,
                                        'lat': 48.854296,
                                        'lon': 2.368122,
                                        'ns': 0,
                                        'pageid': 5423404,
                                        'primary': '',
                                        'title': 'Rue Jean-Beausire'},
                                        {'dist': 257.8,
                                        'lat': 48.85472,
                                        'lon': 2.37083,
                                        'ns': 0,
                                        'pageid': 5348677,
                                        'primary': '',
                                        'title': 'Rue Daval'},
                                        {'dist': 259.2,
                                        'lat': 48.850127,
                                        'lon': 2.369746,
                                        'ns': 0,
                                        'pageid': 2945021,
                                        'primary': '',
                                        'title': 'IGN FI'},
                                        {'dist': 260.2,
                                        'lat': 48.851286,
                                        'lon': 2.373298,
                                        'ns': 0,
                                        'pageid': 4576312,
                                        'primary': '',
                                        'title': 'Passage du Chantier'},
                                        {'dist': 263.3,
                                        'lat': 48.852,
                                        'lon': 2.37374,
                                        'ns': 0,
                                        'pageid': 4105367,
                                        'primary': '',
                                        'title': 'Fontaine de Charonne'},
                                        {'dist': 267.7,
                                        'lat': 48.8548,
                                        'lon': 2.36949,
                                        'ns': 0,
                                        'pageid': 12306106,
                                        'primary': '',
                                        'title': 'Maison Caron de Beaumarchais'},
                                        {'dist': 272.3,
                                        'lat': 48.854051,
                                        'lon': 2.373004,
                                        'ns': 0,
                                        'pageid': 5419993,
                                        'primary': '',
                                        'title': 'Passage Louis-Philippe'},
                                        {'dist': 273.6,
                                        'lat': 48.854266,
                                        'lon': 2.3677,
                                        'ns': 0,
                                        'pageid': 5419959,
                                        'primary': '',
                                        'title': 'Passage Jean-Beausire'},
                                        {'dist': 290.9,
                                        'lat': 48.852891,
                                        'lon': 2.366288,
                                        'ns': 0,
                                        'pageid': 5422756,
                                        'primary': '',
                                        'title': 'Rue Castex'},
                                        {'dist': 292.3,
                                        'lat': 48.850971,
                                        'lon': 2.366889,
                                        'ns': 0,
                                        'pageid': 5422606,
                                        'primary': '',
                                        'title': 'Rue Bassompierre'},
                                        {'dist': 297.6,
                                        'lat': 48.853543,
                                        'lon': 2.373908,
                                        'ns': 0,
                                        'pageid': 5425046,
                                        'primary': '',
                                        'title': 'Cour Quellard'},
                                        {'dist': 302.3,
                                        'lat': 48.851917,
                                        'lon': 2.366148,
                                        'ns': 0,
                                        'pageid': 4638866,
                                        'primary': '',
                                        'title': 'Rue de la Cerisaie'},
                                        {'dist': 302.3,
                                        'lat': 48.851917,
                                        'lon': 2.366148,
                                        'ns': 0,
                                        'pageid': 11870991,
                                        'primary': '',
                                        'title': 'Hôtel de Lesdiguières (Paris)'},
                                        {'dist': 305.8,
                                        'lat': 48.85333,
                                        'lon': 2.36625,
                                        'ns': 0,
                                        'pageid': 140673,
                                        'primary': '',
                                        'title': 'Temple du Marais'},
                                        {'dist': 311.2,
                                        'lat': 48.853233,
                                        'lon': 2.374282,
                                        'ns': 0,
                                        'pageid': 5425043,
                                        'primary': '',
                                        'title': 'Cour du Panier-Fleuri'}]}}

ARGUMENT_10 = '23299'

EXPECTED_RESULT_10 = (200,
 '  La place de la Bastille est une place de Paris, lieu symbolique de la '
 "Révolution française, où l'ancienne forteresse de la Bastille fut détruite "
 'entre le 14 juillet 1789 et le 14 juillet 1790.    Situation et accès Voies '
 "partant de la place de la Bastille Dans le sens des aiguilles d'une montre "
 "en commençant face à l'ange de la colonne :  la rue Saint-Antoine, se "
 "prolongeant par la rue de Rivoli qui passe par l'Hôtel de Ville et le "
 'Châtelet et mène à la place de la Concorde  la rue de la Bastille  le '
 'boulevard Beaumarchais (menant à la place de la République)  le boulevard '
 'Richard-Lenoir prolongé par le boulevard Jules-Ferry, puis le quai de Valmy, '
 "continuant le canal Saint-Martin qui mène jusqu'à Stalingrad  la rue de la "
 'Roquette, passant par la place Léon…',
 'https://fr.wikipedia.org/wiki/Place_de_la_Bastille')

class MockRequestsGet5:
    def __init__(self, url, params=None):
        self.status_code = 200
    def json(self):
        return {'batchcomplete': '',
                        'query': {'pages': {'23299': {'canonicalurl': 'https://fr.wikipedia.org/wiki/Place_de_la_Bastille',
                                                'contentmodel': 'wikitext',
                                                'editurl': 'https://fr.wikipedia.org/w/index.php?title=Place_de_la_Bastille&action=edit',
                                                'extract': '<p class="mw-empty-elt">\n'
                                                                '</p>\n'
                                                                '<p>La <b>place de la Bastille</b> '
                                                                'est une place de Paris, lieu '
                                                                'symbolique de la Révolution '
                                                                "française, où l'ancienne forteresse "
                                                                'de la Bastille fut détruite entre '
                                                                'le <time class="nowrap date-lien" '
                                                                'datetime="1789-07-14" '
                                                                'data-sort-value="1789-07-14">14 '
                                                                'juillet 1789</time> et le <time '
                                                                'class="nowrap date-lien" '
                                                                'datetime="1790-07-14" '
                                                                'data-sort-value="1790-07-14">14 '
                                                                'juillet 1790</time>.\n'
                                                                '</p>\n'
                                                                '\n'
                                                                '\n'
                                                                '<h2><span '
                                                                'id="Situation_et_acc.C3.A8s"></span><span '
                                                                'id="Situation_et_accès">Situation '
                                                                'et accès</span></h2>\n'
                                                                '<h3><span '
                                                                'id="Voies_partant_de_la_place_de_la_Bastille">Voies '
                                                                'partant de la place de la '
                                                                'Bastille</span></h3>\n'
                                                                "<p>Dans le sens des aiguilles d'une "
                                                                "montre en commençant face à l'ange "
                                                                'de la colonne&#160;:\n'
                                                                '</p>\n'
                                                                '<ul><li>la rue Saint-Antoine, se '
                                                                'prolongeant par la rue de Rivoli '
                                                                "qui passe par l'Hôtel de Ville et "
                                                                'le Châtelet et mène à la place de '
                                                                'la Concorde&#160;;</li>\n'
                                                                '<li>la rue de la '
                                                                'Bastille&#160;;</li>\n'
                                                                '<li>le boulevard Beaumarchais '
                                                                '(menant à la place de la '
                                                                'République)&#160;;</li>\n'
                                                                '<li>le boulevard Richard-Lenoir '
                                                                'prolongé par le boulevard '
                                                                'Jules-Ferry, puis le quai de Valmy, '
                                                                'continuant le canal Saint-Martin '
                                                                "qui mène jusqu'à "
                                                                'Stalingrad&#160;;</li>\n'
                                                                '<li>la rue de la Roquette, passant '
                                                                'par la place Léon</li></ul>…',
                                                'fullurl': 'https://fr.wikipedia.org/wiki/Place_de_la_Bastille',
                                                'lastrevid': 175421466,
                                                'length': 22434,
                                                'ns': 0,
                                                'pageid': 23299,
                                                'pagelanguage': 'fr',
                                                'pagelanguagedir': 'ltr',
                                                'pagelanguagehtmlcode': 'fr',
                                                'title': 'Place de la Bastille',
                                                'touched': '2021-01-31T14:44:29Z'}}},
                        'warnings': {'extracts': {'*': 'HTML may be malformed and/or unbalanced and '
                                                        'may omit inline images. Use at your own risk. '
                                                        'Known problems are listed at '
                                                        'https://www.mediawiki.org/wiki/Special:MyLanguage/Extension:TextExtracts#Caveats.'}}}